# Generated by Django 2.0 on 2018-02-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of blog posting', max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
